#
# 	Copyright (c) 2026, VeriSign, Inc.
# 	All rights reserved.
#
# 	Redistribution and use in source and binary forms, with or without
# 	modification, are permitted (subject to the limitations in the disclaimer
# 	below) provided that the following conditions are met:
#
# 		* Redistributions of source code must retain the above copyright notice,
# 		this list of conditions and the following disclaimer.
#
# 		* Redistributions in binary form must reproduce the above copyright
# 		notice, this list of conditions and the following disclaimer in the
# 		documentation and/or other materials provided with the distribution.
#
# 		* Neither the name of the copyright holder nor the names of its
# 		contributors may be used to endorse or promote products derived from this
# 		software without specific prior written permission.
#
# 	NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY
# 	THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
# 	CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# 	LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# 	PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# 	CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# 	EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# 	PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# 	BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
# 	IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# 	ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# 	POSSIBILITY OF SUCH DAMAGE.
#


# Use an official fedora minimal base project container
FROM registry.fedoraproject.org/fedora-minimal:latest AS base_image

USER root
RUN dnf -y install gcc git perl make cmake libtool autoconf

RUN echo "/usr/local/lib64" > /etc/ld.so.conf.d/crypto.conf

# Set the working directory in the container
RUN mkdir -p /usr/local/app
WORKDIR /usr/local/app

#######################################
# Build the latest OpenSSL image
#######################################
RUN git clone https://github.com/openssl/openssl.git --branch openssl-3.6.0
RUN cd openssl && \
    ./config && \
    make && \
    make install_sw

#######################################
# Build the latest LIBOQS image
#######################################
RUN git clone https://github.com/open-quantum-safe/liboqs --branch 0.14.0
RUN cd liboqs && \
   mkdir -p build && \
   cd build && \
   rm -rf CMakeCache.txt && \
   cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=/usr/local .. && \
   make && \
   make install



#######################################
# Build the minimal image
#######################################
FROM registry.fedoraproject.org/fedora-minimal:latest AS core-pqc

RUN echo "/usr/local/lib64" > /etc/ld.so.conf.d/crypto.conf
# Get the include files
COPY --from=base_image /usr/local/include /usr/local/include
# Get the binary files (e.g. openssl)
COPY --from=base_image /usr/local/lib64 /usr/local/lib64
RUN ldconfig -v
