#
# 	Copyright (c) 2026, VeriSign, Inc.
# 	All rights reserved.
#
# 	Redistribution and use in source and binary forms, with or without
# 	modification, are permitted (subject to the limitations in the disclaimer
# 	below) provided that the following conditions are met:
#
# 		* Redistributions of source code must retain the above copyright notice,
# 		this list of conditions and the following disclaimer.
#
# 		* Redistributions in binary form must reproduce the above copyright
# 		notice, this list of conditions and the following disclaimer in the
# 		documentation and/or other materials provided with the distribution.
#
# 		* Neither the name of the copyright holder nor the names of its
# 		contributors may be used to endorse or promote products derived from this
# 		software without specific prior written permission.
#
# 	NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY
# 	THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
# 	CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# 	LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# 	PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# 	CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# 	EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# 	PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# 	BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
# 	IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# 	ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# 	POSSIBILITY OF SUCH DAMAGE.
#

# Use the pqc_base image that has the depenencies available
FROM pqc_base:latest AS base_image

USER root
RUN dnf -y install gcc git make libtool autoconf bc

# Set the working directory in the container
RUN mkdir -p /usr/local/app
WORKDIR /usr/local/app

#######################################
# Build the MTL Mode Library
#######################################
COPY examples/ /usr/local/app/examples
COPY src/ /usr/local/app/src
COPY test/ /usr/local/app/test
COPY *.* /usr/local/app/

RUN autoreconf --install && \
    ./configure --libdir=/usr/local/lib64 && \
    make && \
    make install

#######################################
# Build the minimal image
#######################################
FROM pqc_base:latest AS core_pqc

COPY --from=base_image /usr/local/lib64 /usr/local/lib64
COPY --from=base_image /usr/local/include /usr/local/include
RUN ldconfig -v