noinst_LTLIBRARIES = libmtllib.la
libmtllib_la_SOURCES = mtl.c mtllib.c mtllib_util.c mtl_abstract.c mtl_node_set.c mtl_util.c mtl_buffer.c mtllib_buffer.c mtl_hash.c
libmtllib_la_LDFLAGS = -static

lib_LTLIBRARIES = libmtlslib.la
libmtlslib_la_SOURCES = mtl.c mtllib.c mtllib_util.c mtl_abstract.c mtl_node_set.c mtl_util.c mtl_buffer.c mtllib_buffer.c mtl_hash.c
pkginclude_HEADERS=mtl.h mtl_node_set.h mtllib.h mtllib_util.h mtllib_buffer.h mtl_hash.h mtl_util.h mtllib_status.h mtl_status.h mtl_index.h
